api/config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/preview-emails"
  end

  constraints subdomain: ENV.fetch("AUTH_SUBDOMAIN", "auth") do
    devise_for :users,
      controllers: {
        omniauth_callbacks: "users/omniauth_callbacks",
      },
      path: "",
      path_names: { sign_up: "sign-up", sign_in: "sign-in", sign_out: "sign-out" },
      skip: [:confirmations, :registrations, :sessions]

    devise_scope :user do
      # registrations
      get "/sign-up", to: "users/registrations#new", as: :new_user_registration
      post "/", to: "users/registrations#create", as: :user_registration
      # confirmations
      get "/confirmation", to: "users/confirmations#show", as: :user_confirmation
      # sessions
      get "/sign-in", to: "users/sessions#new", as: :new_user_session
      post "/sign-in", to: "users/sessions#create", as: :user_session
      get "/desktop/sign-in", to: "users/sessions#desktop", as: :desktop_session
      get "/sign-in/otp", to: "users/otp/sessions#new"
      post "/sign-in/otp", to: "users/otp/sessions#create"
      get "/sign-in/recovery-code", to: "users/recovery_code/sessions#new"
      post "/sign-in/recovery-code", to: "users/recovery_code/sessions#create"
    end

    get "/", to: redirect("/sign-in"), as: :auth_root
    get "/sign-in/desktop", to: "users/desktop/sessions#new", as: :new_desktop_session
    get "/sign-in/desktop/open", to: "users/desktop/sessions#show", as: :open_desktop_session
    post "/sign-in/figma", to: "users/figma/sessions#create", as: :create_figma_session
    get "/sign-in/figma/open", to: "users/figma/sessions#show", as: :open_figma_session

    use_doorkeeper do
      skip_controllers :applications
      controllers authorizations: "doorkeeper/custom_authorizations"
    end

    namespace :integrations do
      resource :auth, only: :new
    end
  end

  constraints subdomain: "admin" do
    scope module: "admin", path: "admin" do
      authenticate :user, lambda { |u| u.staff? } do
        mount Sidekiq::Web => "/sidekiq"
      end

      get "/", to: "admin#index", as: "admin"

      scope module: "features" do
        resources :features, only: [:index, :create, :destroy, :show], param: :name do
          resources :users, only: [:create, :destroy]
          resource :user_search, only: [:show]
          resources :organizations, only: [:create, :destroy], param: :slug
          resource :organization_search, only: [:show]
          resources :actors, only: [:destroy]
          resources :groups, only: [:create, :destroy], param: :name
          resource :enablement, only: [:create, :destroy]

          resources :logs, only: [] do
            resource :rollback, only: [:create]
          end
        end
      end

      scope module: "demo_orgs" do
        resources :demo_orgs, only: [:index, :create]
      end
    end

    get "/", to: redirect("/admin")
  end

  scope module: "api/v1", path: "v1", defaults: { format: :json } do
    # allows organizations to be used as an authorization scope for oauth access tokens
    devise_for :organizations, skip: :all

    get "/organization-by-token/:token", to: "public_organizations#show", as: :public_organization
    post "/organizations", to: "organizations#create"

    resources :public_projects, only: [:show], param: :token

    resources :image_urls, only: :create

    resources :organization_memberships, only: [:index] do
      collection do
        resource :reorder, only: [:update], controller: "organization_memberships/reorders", as: :reorder_organization_memberships
      end
    end

    scope "/organizations/:org_slug", as: :organization do
      get "/", to: "organizations#show"
      patch "/", to: "organizations#update"
      put "/", to: "organizations#update"
      put "/reset-invite-token", to: "organizations#reset_invite_token", as: :reset_invite_token
      patch "/reset-invite-token", to: "organizations#reset_invite_token"
      delete "/", to: "organizations#destroy"
      post "/join/:token", to: "organizations#join", as: :join
      put "/onboard", to: "organizations#onboard", as: :onboard_organization
      get "/avatar/presigned-fields", to: "organizations#avatar_presigned_fields", as: :avatar_presigned_fields
      # enable/disable sso
      post "/sso", to: "organizations/sso#create", as: :sso
      delete "/sso", to: "organizations/sso#destroy"

      get "/invitations", to: "organization_invitations#index", as: :invitations
      post "/invitations", to: "organization_invitations#create"
      get "/invitations/:invite_token", to: "organization_invitations#show", as: :invitation
      # DEPRECATED: Use POST /invitations_by_token/:invite_token/accept instead
      post "/invitations/:id/accept", to: "organization_invitations#accept", as: :accept_invitation
      delete "/invitations/:id", to: "organization_invitations#destroy"

      # Notifications
      get "/members/me/notifications", to: "notifications#index", as: :notifications
      delete "/members/me/notifications/:id", to: "notifications#destroy", as: :notification
      post "/members/me/notifications/:notification_id/read", to: "notifications/reads#create", as: :notification_read
      delete "/members/me/notifications/:notification_id/read", to: "notifications/reads#destroy"
      post "/members/me/notifications/mark_all_read", to: "notifications/mark_all_reads#create", as: :notification_mark_all_read
      post "/members/me/notifications/delete_all", to: "notifications/delete_all#create", as: :notification_delete_all

      namespace :organization_memberships, path: "members", as: :membership do
        scope "me" do
          resource :index_views, only: [:update]
          resource :slack_notification_preference, only: [:show, :create, :destroy]
          resource :statuses, only: [:create, :update, :destroy] do
            get :index
          end
          resources :viewer_posts, only: [:index]
          resources :viewer_notes, only: [:index]
          resources :for_me_posts, only: [:index]
          resources :for_me_notes, only: [:index]
          resources :personal_draft_posts, only: [:index]
          resource :personal_call_room, only: [:show]
          resources :archived_notifications, only: [:index]
          resource :data_export, only: [:create]
        end
      end

      scope "members/me" do
        resources :notifications, only: [] do
          resource :archive, only: [:destroy], controller: "notifications/archives"
        end
      end

      resources :members, only: [:index, :show], param: :username, controller: "organization_members" do
        resources :project_memberships, only: [:index], controller: "organization_memberships/project_memberships"
        resource :project_membership_list, only: [:update], controller: "organization_memberships/project_membership_lists"
      end

      resource :invitation_url, only: [:show]

      get "/members/:username/posts", to: "organization_members#posts", as: :member_posts
      patch "/members/:id", to: "organization_members#update"
      put "/members/:id", to: "organization_members#update"
      patch "/members/:id/reactivate", to: "organization_members#reactivate", as: :member_reactivate
      put "/members/:id/reactivate", to: "organization_members#reactivate"
      delete "/members/:id", to: "organization_members#destroy"

      get "/membership-requests", to: "organization_membership_requests#index", as: :membership_requests
      get "/membership-request", to: "organization_membership_requests#show", as: :membership_request
      post "/membership-requests", to: "organization_membership_requests#create"
      post "/membership-requests/:id/approve", to: "organization_membership_requests#approve", as: :approve_membership_request
      post "/membership-requests/:id/decline", to: "organization_membership_requests#decline", as: :decline_membership_request

      # posts
      get "/posts", to: "posts#index", as: :posts
      get "/posts/presigned-fields", to: "posts#presigned_fields", as: :post_presigned_fields
      post "/posts", to: "posts#create"
      get "/posts/:post_id", to: "posts#show", as: :post
      patch "/posts/:post_id", to: "posts#update"
      put "/posts/:post_id", to: "posts#update"
      delete "/posts/:post_id", to: "posts#destroy"

      # post subscriptions
      post "/posts/:post_id/subscribe", to: "posts#subscribe", as: :post_subscribe
      delete "/posts/:post_id/unsubscribe", to: "posts#unsubscribe", as: :post_unsubscribe

      # post feedback requests
      post "/posts/:post_id/feedback_requests", to: "posts/post_feedback_requests#create", as: :post_feedback_requests
      delete "/posts/:post_id/feedback_requests/:id", to: "posts/post_feedback_requests#destroy", as: :post_feedback_request
      post "/posts/:post_id/feedback-dismissals", to: "posts/feedback_dismissals#create", as: :post_feedback_dismissals

      # post reactions
      post "/posts/:post_id/reactions", to: "posts/post_reactions#create", as: :post_reactions

      # post views
      get "/posts/:post_id/views", to: "posts/post_views#index", as: :post_views
      post "/posts/:post_id/views", to: "posts/post_views#create"

      # post comments
      get "/posts/:post_id/comments", to: "posts/post_comments#index", as: :post_comments
      post "/posts/:post_id/comments", to: "posts/post_comments#create"
      # TODO: replace #create with #create2 once front-end is switched and desktop clients update
      post "/posts/:post_id/comments2", to: "posts/post_comments#create", as: :post_comments2

      # post canvas comments
      get "/posts/:post_id/canvas_comments", to: "posts/post_canvas_comments#index", as: :post_canvas_comments

      resources :posts, only: [] do

api/app/controllers/admin/features/actors_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class ActorsController < BaseController
      def destroy
        actor = Flipper::Actor.new(params[:id])
        Flipper.disable(feature_name, actor)
        flash[:notice] = "Disabled #{feature_name} for #{actor.flipper_id}"
        redirect_to(feature_path(feature_name))
      end

      private

      def feature_name
        params[:feature_name]
      end
    end
  end
end

api/app/controllers/admin/features/enablements_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class EnablementsController < BaseController
      def create
        feature.enable
        redirect_to(feature_path(feature_name))
      end

      def destroy
        feature.disable
        flash[:notice] = "Fully disabled #{feature_name}"
        redirect_to(feature_path(feature_name))
      end

      private

      def feature_name
        params[:feature_name]
      end

      def feature
        Flipper.feature(feature_name)
      end
    end
  end
end

api/app/controllers/admin/features/features_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class FeaturesController < BaseController
      before_action :set_breadcrumbs

      def index
        render("admin/features/features/index")
      end

      def create
        feature.add
        flash[:notice] = "Created #{feature.name} feature"
        redirect_to(feature_path(feature.name))
      end

      def destroy
        feature.remove
        flash[:notice] = "Deleted #{feature.name} feature"
        redirect_to(features_path)
      end

      def show
        add_breadcrumb("Feature")

        enabled_actors = feature.actors_value.map do |item|
          model_name, id = item.split(";")
          model = model_name.constantize
          model.find_by(id: id) || NullActor.build(model: model, id: id)
        end
        enabled_users = enabled_actors.select { |actor| actor.is_a?(User) }.sort_by { |user| user.email.downcase }
        enabled_orgs = enabled_actors.select { |actor| actor.is_a?(Organization) }.sort_by { |org| org.name.downcase }
        enabled_groups, enablable_groups = Flipper.groups.partition { |group| group.in?(feature.enabled_groups) }

        render("admin/features/features/show", locals: {
          feature: feature,
          enabled_users: enabled_users,
          enabled_orgs: enabled_orgs,
          enabled_groups: enabled_groups,
          enablable_groups: enablable_groups,
          logs: FlipperAuditLog.includes(:user).where(feature_name: feature.name).order(created_at: :desc),
        })
      end

      private

      def feature
        Flipper.feature(params[:name])
      end

      def set_breadcrumbs
        add_breadcrumb("Features", features_path)
      end
    end
  end
end

api/app/controllers/admin/features/groups_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class GroupsController < BaseController
      def create
        Flipper.enable_group(feature_name, group_name)
        flash[:notice] = "Enabled #{feature_name} for #{group_name}"
        redirect_to(feature_path(feature_name))
      end

      def destroy
        Flipper.disable_group(feature_name, group_name)
        flash[:notice] = "Disabled #{feature_name} for #{group_name}"
        redirect_to(feature_path(feature_name))
      end

      private

      def feature_name
        params[:feature_name]
      end

      def group_name
        params[:name]
      end
    end
  end
end

api/app/controllers/admin/features/organization_searches_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class OrganizationSearchesController < BaseController
      def show
        slugs = Organization
          .where("slug LIKE LOWER(?)", "#{params[:q].downcase}%")
          .reject { |org| org.flipper_id.in?(Flipper.feature(params[:feature_name]).actors_value) }
          .map(&:slug)

        render(partial: "admin/features/features/actor_search_results", locals: { results: slugs })
      end
    end
  end
end

api/app/controllers/admin/features/organizations_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class OrganizationsController < BaseController
      def create
        if org
          Flipper.enable(feature_name, org)
          flash[:notice] = "Enabled #{feature_name} for #{org.slug}"
        else
          flash[:alert] = "No organization found with that slug"
        end

        redirect_to(feature_path(feature_name))
      end

      def destroy
        if org
          Flipper.disable(feature_name, org)
          flash[:notice] = "Disabled #{feature_name} for #{org.slug}"
        else
          flash[:alert] = "Organization not found"
        end

        redirect_to(feature_path(feature_name))
      end

      private

      def feature_name
        params[:feature_name]
      end

      def org
        Organization.find_by(slug: params[:slug])
      end
    end
  end
end

api/app/controllers/admin/features/rollbacks_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class RollbacksController < BaseController
      def create
        log.rollback_to!
        redirect_to(feature_path(feature_name))
      end

      private

      def log
        FlipperAuditLog.find(params[:log_id])
      end

      def feature_name
        params[:feature_name]
      end
    end
  end
end

api/app/controllers/admin/features/user_searches_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class UserSearchesController < BaseController
      def show
        emails = User
          .where("email LIKE LOWER(?)", "#{params[:q].downcase}%")
          .reject { |user| user.flipper_id.in?(Flipper.feature(params[:feature_name]).actors_value) }
          .map(&:email)

        render(partial: "admin/features/features/actor_search_results", locals: { results: emails })
      end
    end
  end
end

api/app/controllers/admin/features/users_controller.rb
# frozen_string_literal: true

module Admin
  module Features
    class UsersController < BaseController
      def create
        user = User.find_by(email: params[:email])

        if user
          Flipper.enable(feature_name, user)
          flash[:notice] = "Enabled #{feature_name} for #{user.email}"
        else
          flash[:alert] = "No user found with that email"
        end

        redirect_to(feature_path(feature_name))
      end

      def destroy
        user = User.find_by(id: params[:id])

        if user
          Flipper.disable(feature_name, user)
          flash[:notice] = "Disabled #{feature_name} for #{user.email}"
        else
          flash[:alert] = "User not found"
        end

        redirect_to(feature_path(feature_name))
      end

      private

      def feature_name
        params[:feature_name]
      end
    end
  end
end

api/app/controllers/api/v1/organizations/features_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Organizations
      class FeaturesController < V1::BaseController
        extend Apigen::Controller

        skip_before_action :require_authenticated_user, only: :index
        skip_before_action :require_authenticated_organization_membership, only: :index
        skip_before_action :require_org_two_factor_authentication, only: :index

        response code: 200 do
          { features: { type: :string, is_array: true, enum: (Organization::FEATURE_FLAGS + Plan::FEATURES).uniq } }
        end
        def index
          raise ActiveRecord::RecordNotFound unless current_organization

          render(json: { features: current_organization.features }, status: :ok)
        end
      end
    end
  end
end

api/app/views/admin/features/features/_actor_search_results.html.erb
<% results.each do |result| %>
  <li role="option"><%= result %></li>
<% end %>

api/app/views/admin/features/features/index.html.erb
<% @page_title = "Features - Campsite" %>

<h1 class="page-title mb-6">Features</h1>

<% if notice %>
  <div class="notice mb-6">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="error mb-6">
    <%= alert %>
  </div>
<% end %>

<% if Flipper.features.any? %>
  <ul class="mb-6">
    <% Flipper.features.each do |feature| %>
      <li class="mb-1">
        <%= link_to(feature.name, feature_path(feature.name), class: "hover:underline text-link") %> <span class="text-gray-500">
        <% if [:on, :conditional].include?(feature.state) %>
          Enabled
        <% end %>

        <% if feature.groups.any? || feature.actors_value.any? %>
          <span class="text-gray-400">for</span>
        <% end %>
        <% if feature.groups.any? %>
          <%= feature.groups.map(&:name).to_sentence %>
        <% end %>
        <% if feature.groups.any? && feature.actors_value.any? %>
          <span class="text-gray-400">and</span>
        <% end %>
        <% if feature.actors_value.any? %>
          <%= pluralize feature.actors_value.count, "actor" %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else%>
  <div class="text-sm text-secondary mb-5 text-center">No features, yet!</div>
<% end %>

<%= form_with url: features_path do |f| %>
  <div class="form-group mb-3">
    <%= f.label(:name, "New feature name", class: "mb-1") %>
    <%= f.text_field(:name, required: true, class: "mb-1") %>
    <div class="text-xs text-secondary">
      Name should be lower case and snake case.
    </div>
  </div>
  <%= f.submit("Create", class: "btn btn-secondary") %>
<% end %>

api/app/views/admin/features/features/show.html.erb
<% @page_title = "#{feature.name} - Features - Campsite" %>

<h1 class="page-title mb-6"><%= feature.name %></h1>

<% if feature.enabled? %>
  <div class="notice mb-6">
    <%= feature.name %> is fully enabled for everyone
  </div>

  <div class="mt-12">
    <%=
      button_to(
        "Fully disable",
        feature_enablement_path(feature.name),
        class: "btn btn-secondary mb-6",
        method: :delete,
        data: { confirm: Rails.env.production? ? "You are in PRODUCTION. Are you sure you want to fully disable the #{feature.name} feature?" : nil }
      )
    %>

    <%=
      button_to(
        "Delete",
        feature_path(feature.name),
        class: "btn btn-danger",
        method: :delete,
        data: { confirm: Rails.env.production? ? "You are in PRODUCTION. Are you sure you want to delete the #{feature.name} feature?" : nil }
      )
    %>
  </div>
<% else %>
  <% if notice %>
    <div class="notice mb-6">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="error mb-6">
      <%= alert %>
    </div>
  <% end %>

  <div class="w-full">
    <h2 class="text-lg md:text-xl text-primary font-medium mb-3">Enabled users</h2>

    <div class="mb-4">
      <% if enabled_users.any? %>
        <% enabled_users.each do |user| %>
          <div class="flex items-center mt-2 text-primary">
            <% disable_user_path = user.is_a?(Admin::Features::NullUser) ? feature_actor_path(feature.name, user.flipper_id) : feature_user_path(feature.name, user) %>
            <%= button_to disable_user_path, method: :delete, class: "mr-1 flex items-center" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            <% end %>
            <%= user.email %>
          </div>
        <% end %>
        </ul>
      <% else %>
        <div class="text-sm text-secondary">Not enabled for any users.</div>
      <% end %>
    </div>

    <%= form_with url: feature_users_path(feature.name) do |f| %>
      <div class="form-group mb-2">
        <%= f.label(:email, "Add user by email", class: "mb-1") %>
          <auto-complete src="<%= feature_user_search_path(feature.name) %>" for="users-popup">
            <%= f.search_field(:email, class: "autocomplete-input", required: true) %>
            <ul id="users-popup"></ul>
          </auto-complete>
      </div>
      <%= f.submit("Enable", class: "btn btn-secondary") %>
    <% end %>
  </div>

  <div class="divider"></div>

  <div class="w-full">
    <h2 class="text-lg md:text-xl text-primary font-medium mb-3">Enabled organizations</h2>

    <div class="mb-4">
      <% if enabled_orgs.any? %>
        <% enabled_orgs.each do |org| %>
          <div class="flex items-center mt-2 text-primary">
            <% disable_org_path = org.is_a?(Admin::Features::NullOrganization) ? feature_actor_path(feature.name, org.flipper_id) : feature_organization_path(feature.name, org) %>
            <%= button_to disable_org_path, method: :delete, class: "mr-1 flex items-center" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            <% end %>
            <%= org.name %>
          </div>
        <% end %>
      <% else %>
        <div class="text-sm text-secondary">Not enabled for any organizations.</div>
      <% end %>
    </div>

    <%= form_with url: feature_organizations_path(feature.name) do |f| %>
      <div class="form-group mb-2">
        <%= f.label(:slug, "Add organization by slug", class: "mb-1") %>
        <auto-complete src="<%= feature_organization_search_path(feature.name) %>" for="orgs-popup">
          <%= f.search_field(:slug, class: "autocomplete-input", required: true) %>
          <ul id="orgs-popup"></ul>
        </auto-complete>
      </div>
      <%= f.submit("Enable", class: "btn btn-secondary") %>
    <% end %>
  </div>

  <div class="divider"></div>

  <div class="w-full mb-6">
    <h2 class="text-lg md:text-xl text-primary font-medium mb-3">Enabled groups</h2>

    <div class="mb-4">
      <% if enabled_groups.any? %>
        <% enabled_groups.each do |group| %>
          <div class="flex items-center mt-2 text-primary">
            <%= button_to feature_group_path(feature.name, group.name), method: :delete, class: "mr-1 flex items-center" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            <% end %>
            <%= group.name %>
          </div>
        <% end %>
      <% else %>
        <div class="text-sm text-secondary">Not enabled for any groups.</div>
      <% end %>
    </div>

    <% if enablable_groups.any? %>
      <%= form_with url: feature_groups_path(feature.name) do |f| %>
        <div class="form-group mb-2">
          <%= label(:name, "Add group by name") %>
          <%= f.select :name, enablable_groups.map(&:name) %>
        </div>
        <%= f.submit("Enable", class: "btn btn-secondary") %>
      <% end %>
    <% else %>
      <div class="text-sm text-secondary">No more enablable groups.</div>
    <% end %>
  </div>

  <div class="divider"></div>

  <div class="mt-12">
    <%=
      button_to(
        "Fully enable",
        feature_enablement_path(feature.name),
        class: "btn btn-secondary mb-6",
        data: { confirm: Rails.env.production? ? "You are in PRODUCTION. Are you sure you want to fully enable the #{feature.name} feature?" : nil }
      )
    %>

    <%=
      button_to(
        "Fully disable",
        feature_enablement_path(feature.name),
        class: "btn btn-secondary",
        method: :delete,
        data: { confirm: Rails.env.production? ? "You are in PRODUCTION. Are you sure you want to fully disable the #{feature.name} feature?" : nil }
      )
    %>
  </div>

  <div class="divider"></div>

  <div class="w-full mb-6">
    <h2 class="text-lg md:text-xl text-primary font-medium mb-3">Delete feature</h2>
    <%=
      button_to(
        "Delete",
        feature_path(feature.name),
        class: "btn btn-danger",
        method: :delete,
        data: { confirm: Rails.env.production? ? "You are in PRODUCTION. Are you sure you want to delete the #{feature.name} feature?" : nil }
      )
    %>
  </div>
<% end %>

<div class="divider"></div>

<div class="w-full mb-6">
  <h2 class="text-lg md:text-xl text-primary font-medium mb-3">History</h2>
  <ul class="flex flex-col gap-4">
    <% logs.each_with_index do |log, i| %>
      <li class="flex gap-2">
        <div><%= log.accessory %></div>
        <div class="flex flex-col gap-0.5">
          <div>
            <span class="whitespace-nowrap"><%= log.user_display_name %></span>
            <%= log.action %>
            the <span class="whitespace-nowrap"><%= log.feature_name %></span> feature flag
            <% if log.target_display_name %>
              for <span class="whitespace-nowrap"><%= log.target_display_name %></span>
            <% end %>
          </div>
          <div class="flex gap-1 text-sm text-secondary">
            <relative-time datetime="<%= log.created_at.iso8601 %>"><%= l(log.created_at) %></relative-time>
            <% unless i == 0 %>
              ∙
              <%=
                button_to(
                  "Rollback to here",
                  feature_log_rollback_path(feature.name, log.id),
                  class: "text-link hover:underline",
                  method: :post,
                  data: { confirm: Rails.env.production? ? "You are in PRODUCTION. Are you sure you want to rollback to this point in time?" : nil }
                )
              %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>