api/config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/preview-emails"
  end

  constraints subdomain: ENV.fetch("AUTH_SUBDOMAIN", "auth") do
    devise_for :users,
      controllers: {
        omniauth_callbacks: "users/omniauth_callbacks",
      },
      path: "",
      path_names: { sign_up: "sign-up", sign_in: "sign-in", sign_out: "sign-out" },
      skip: [:confirmations, :registrations, :sessions]

    devise_scope :user do
      # registrations
      get "/sign-up", to: "users/registrations#new", as: :new_user_registration
      post "/", to: "users/registrations#create", as: :user_registration
      # confirmations
      get "/confirmation", to: "users/confirmations#show", as: :user_confirmation
      # sessions
      get "/sign-in", to: "users/sessions#new", as: :new_user_session
      post "/sign-in", to: "users/sessions#create", as: :user_session
      get "/desktop/sign-in", to: "users/sessions#desktop", as: :desktop_session
      get "/sign-in/otp", to: "users/otp/sessions#new"
      post "/sign-in/otp", to: "users/otp/sessions#create"
      get "/sign-in/recovery-code", to: "users/recovery_code/sessions#new"
      post "/sign-in/recovery-code", to: "users/recovery_code/sessions#create"
    end

    get "/", to: redirect("/sign-in"), as: :auth_root
    get "/sign-in/desktop", to: "users/desktop/sessions#new", as: :new_desktop_session
    get "/sign-in/desktop/open", to: "users/desktop/sessions#show", as: :open_desktop_session
    post "/sign-in/figma", to: "users/figma/sessions#create", as: :create_figma_session
    get "/sign-in/figma/open", to: "users/figma/sessions#show", as: :open_figma_session

    use_doorkeeper do
      skip_controllers :applications
      controllers authorizations: "doorkeeper/custom_authorizations"
    end

    namespace :integrations do
      resource :auth, only: :new
    end
  end

  constraints subdomain: "admin" do
    scope module: "admin", path: "admin" do
      authenticate :user, lambda { |u| u.staff? } do
        mount Sidekiq::Web => "/sidekiq"
      end

      get "/", to: "admin#index", as: "admin"

      scope module: "features" do
        resources :features, only: [:index, :create, :destroy, :show], param: :name do
          resources :users, only: [:create, :destroy]
          resource :user_search, only: [:show]
          resources :organizations, only: [:create, :destroy], param: :slug
          resource :organization_search, only: [:show]
          resources :actors, only: [:destroy]
          resources :groups, only: [:create, :destroy], param: :name
          resource :enablement, only: [:create, :destroy]

          resources :logs, only: [] do
            resource :rollback, only: [:create]
          end
        end
      end

      scope module: "demo_orgs" do
        resources :demo_orgs, only: [:index, :create]
      end
    end

    get "/", to: redirect("/admin")
  end

  scope module: "api/v1", path: "v1", defaults: { format: :json } do
    # allows organizations to be used as an authorization scope for oauth access tokens
    devise_for :organizations, skip: :all

    get "/organization-by-token/:token", to: "public_organizations#show", as: :public_organization
    post "/organizations", to: "organizations#create"

    resources :public_projects, only: [:show], param: :token

    resources :image_urls, only: :create

    resources :organization_memberships, only: [:index] do
      collection do
        resource :reorder, only: [:update], controller: "organization_memberships/reorders", as: :reorder_organization_memberships
      end
    end

    scope "/organizations/:org_slug", as: :organization do
      get "/", to: "organizations#show"
      patch "/", to: "organizations#update"
      put "/", to: "organizations#update"
      put "/reset-invite-token", to: "organizations#reset_invite_token", as: :reset_invite_token
      patch "/reset-invite-token", to: "organizations#reset_invite_token"
      delete "/", to: "organizations#destroy"
      post "/join/:token", to: "organizations#join", as: :join
      put "/onboard", to: "organizations#onboard", as: :onboard_organization
      get "/avatar/presigned-fields", to: "organizations#avatar_presigned_fields", as: :avatar_presigned_fields
      # enable/disable sso
      post "/sso", to: "organizations/sso#create", as: :sso
      delete "/sso", to: "organizations/sso#destroy"

      get "/invitations", to: "organization_invitations#index", as: :invitations
      post "/invitations", to: "organization_invitations#create"
      get "/invitations/:invite_token", to: "organization_invitations#show", as: :invitation
      # DEPRECATED: Use POST /invitations_by_token/:invite_token/accept instead
      post "/invitations/:id/accept", to: "organization_invitations#accept", as: :accept_invitation
      delete "/invitations/:id", to: "organization_invitations#destroy"

      # Notifications
      get "/members/me/notifications", to: "notifications#index", as: :notifications
      delete "/members/me/notifications/:id", to: "notifications#destroy", as: :notification
      post "/members/me/notifications/:notification_id/read", to: "notifications/reads#create", as: :notification_read
      delete "/members/me/notifications/:notification_id/read", to: "notifications/reads#destroy"
      post "/members/me/notifications/mark_all_read", to: "notifications/mark_all_reads#create", as: :notification_mark_all_read
      post "/members/me/notifications/delete_all", to: "notifications/delete_all#create", as: :notification_delete_all

      namespace :organization_memberships, path: "members", as: :membership do
        scope "me" do
          resource :index_views, only: [:update]
          resource :slack_notification_preference, only: [:show, :create, :destroy]
          resource :statuses, only: [:create, :update, :destroy] do
            get :index
          end
          resources :viewer_posts, only: [:index]
          resources :viewer_notes, only: [:index]
          resources :for_me_posts, only: [:index]
          resources :for_me_notes, only: [:index]
          resources :personal_draft_posts, only: [:index]
          resource :personal_call_room, only: [:show]
          resources :archived_notifications, only: [:index]
          resource :data_export, only: [:create]
        end
      end

      scope "members/me" do
        resources :notifications, only: [] do
          resource :archive, only: [:destroy], controller: "notifications/archives"
        end
      end

      resources :members, only: [:index, :show], param: :username, controller: "organization_members" do
        resources :project_memberships, only: [:index], controller: "organization_memberships/project_memberships"
        resource :project_membership_list, only: [:update], controller: "organization_memberships/project_membership_lists"
      end

      resource :invitation_url, only: [:show]

      get "/members/:username/posts", to: "organization_members#posts", as: :member_posts
      patch "/members/:id", to: "organization_members#update"
      put "/members/:id", to: "organization_members#update"
      patch "/members/:id/reactivate", to: "organization_members#reactivate", as: :member_reactivate
      put "/members/:id/reactivate", to: "organization_members#reactivate"
      delete "/members/:id", to: "organization_members#destroy"

      get "/membership-requests", to: "organization_membership_requests#index", as: :membership_requests
      get "/membership-request", to: "organization_membership_requests#show", as: :membership_request
      post "/membership-requests", to: "organization_membership_requests#create"
      post "/membership-requests/:id/approve", to: "organization_membership_requests#approve", as: :approve_membership_request
      post "/membership-requests/:id/decline", to: "organization_membership_requests#decline", as: :decline_membership_request

      # posts
      get "/posts", to: "posts#index", as: :posts
      get "/posts/presigned-fields", to: "posts#presigned_fields", as: :post_presigned_fields
      post "/posts", to: "posts#create"
      get "/posts/:post_id", to: "posts#show", as: :post
      patch "/posts/:post_id", to: "posts#update"
      put "/posts/:post_id", to: "posts#update"
      delete "/posts/:post_id", to: "posts#destroy"

      # post subscriptions
      post "/posts/:post_id/subscribe", to: "posts#subscribe", as: :post_subscribe
      delete "/posts/:post_id/unsubscribe", to: "posts#unsubscribe", as: :post_unsubscribe

      # post feedback requests
      post "/posts/:post_id/feedback_requests", to: "posts/post_feedback_requests#create", as: :post_feedback_requests
      delete "/posts/:post_id/feedback_requests/:id", to: "posts/post_feedback_requests#destroy", as: :post_feedback_request
      post "/posts/:post_id/feedback-dismissals", to: "posts/feedback_dismissals#create", as: :post_feedback_dismissals

      # post reactions
      post "/posts/:post_id/reactions", to: "posts/post_reactions#create", as: :post_reactions

      # post views
      get "/posts/:post_id/views", to: "posts/post_views#index", as: :post_views
      post "/posts/:post_id/views", to: "posts/post_views#create"

      # post comments
      get "/posts/:post_id/comments", to: "posts/post_comments#index", as: :post_comments
      post "/posts/:post_id/comments", to: "posts/post_comments#create"
      # TODO: replace #create with #create2 once front-end is switched and desktop clients update
      post "/posts/:post_id/comments2", to: "posts/post_comments#create", as: :post_comments2

      # post canvas comments
      get "/posts/:post_id/canvas_comments", to: "posts/post_canvas_comments#index", as: :post_canvas_comments

      resources :posts, only: [] do

api/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Campsite" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "/favicon.ico" %>
    <%= favicon_link_tag "/favicon.svg" %>

    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192" />
    <link rel="icon" type="image/png" href="/android-chrome-512x512.png" sizes="512x512" />

    <% unless Rails.env.test? %>
      <%= stylesheet_link_tag "application" %>
      <%= javascript_include_tag "application", defer: true %>
    <% end %>
  </head>

  <body class="w-full min-h-screen">
    <div class="p-2 bg-primary w-full flex flex-col justify-center text-primary text-sm border-b border-secondary">
      <div class="w-full text-center">
        <span class="font-semibold"><%= Rails.env.titleize %> sha:</span> <code><a target="_blank" class="text-link" href="https://github.com/campsite/campsite/commit/<%= ENV["RELEASE_SHA"] %>"><%= ENV["RELEASE_SHA"] %></a></code>
      </div>
    </div>

    <main class="bg-primary min-h-screen">
      <div class="max-w-lg mx-auto px-4 py-10">
        <div class="page-title-container">
          <svg width="49" height="20" viewBox="0 0 49 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0.201982 21.9532L13.7942 0.654571C14.0531 0.248924 14.5245 0 15.0338 0H37.1765C38.2907 0 38.9824 1.12038 38.4161 2.00776L24.8238 23.3064C24.565 23.7121 24.0936 23.961 23.5843 23.961H1.44157C0.327401 23.961 -0.364321 22.8406 0.201982 21.9532Z" fill="currentColor"/>
            <path d="M32.0309 23.9609H47.4978C48.5832 23.9609 49.2781 22.8922 48.7691 22.0055L41.4653 9.28149C40.9386 8.36398 39.5292 8.33304 38.9561 9.22642L30.793 21.9505C30.2237 22.8378 30.9152 23.9609 32.0309 23.9609Z" fill="currentColor"/>
          </svg>

          <div class="flex items-center justify-start mt-1 text-sm">
            <%= link_to 'Admin', admin_path, class: "hover:underline font-bold" %>
            <% breadcrumbs.each do |crumb| %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 mx-1">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
              </svg>
            
              <% if crumb.link? && crumb != breadcrumbs.last %>
                <%= link_to crumb.name, crumb.path, class: "hover:underline font-bold" %>
              <% else %>
                <span class="text-sm text-secondary">
                  <%= crumb.name %>
                </span>
              <% end %>
            <% end %>
          </div>
        </div>

        <%= yield %>
      </div>
    </main>

    <% unless Rails.env.test? %>
      <%= javascript_include_tag "autocomplete" %>
      <%= javascript_include_tag "relative-time" %>
      <%= javascript_include_tag "rails-ujs" %>
    <% end %>
  </body>
</html>

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Campsite" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "/favicon.ico" %>
    <%= favicon_link_tag "/favicon.svg" %>

    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192" />
    <link rel="icon" type="image/png" href="/android-chrome-512x512.png" sizes="512x512" />

    <% unless Rails.env.test? %>
      <%= stylesheet_link_tag "application" %>
      <%= javascript_include_tag "application", defer: true %>
    <% end %>
  </head>

  <body>
    <header class="drag h-14 absolute w-full"></header>
    <%= yield %>
    <%= yield(:javascript) %>
  </body>
</html>